dist: precise
language: node_js
node_js:
  - 6
  - 8
cache:
  directories:
  - node_modules
install: npm install
env:
  global:
    - USE_YARN=no
notifications:
    slack: fullstackacademy:Go9zrVGvhitNEJKH6UN6WdtS
